name: Application cron to deploy auto the website

on:
  - pull_request
  - workflow_dispatch

jobs:
  build-caddy-validator:
    environment: IGP
    env:
      IGP: ${{ secrets.IGP }}
      IGU: ${{ secrets.IGU }}
    name: Agregate and redeploy if necessary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Install python3
        uses: actions/setup-python@v3
      - name: Install the insta DL
        env:
          IGP: ${{ secrets.IGP }}
          IGU: ${{ secrets.IGU }}
        run: pip3 install instaloader
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run the IG agregator
        working-directory: ./agregator
        run: go run nfr.go
      - name: Run the tickets agregator
        working-directory: ./agregator/tickets
        run: go run tickets.go
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'Update triggered from the GA'